,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/46067,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46067/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46067/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46067/events,https://github.com/pandas-dev/pandas/issues/46067,1144384928,I_kwDOAA0YD85ENe2g,46067,BUG: incorrect spacing with 'background-color' and Styler.to_latex(convert_css=True),"{'login': 'andreostrovsky', 'id': 18727813, 'node_id': 'MDQ6VXNlcjE4NzI3ODEz', 'avatar_url': 'https://avatars.githubusercontent.com/u/18727813?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/andreostrovsky', 'html_url': 'https://github.com/andreostrovsky', 'followers_url': 'https://api.github.com/users/andreostrovsky/followers', 'following_url': 'https://api.github.com/users/andreostrovsky/following{/other_user}', 'gists_url': 'https://api.github.com/users/andreostrovsky/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/andreostrovsky/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/andreostrovsky/subscriptions', 'organizations_url': 'https://api.github.com/users/andreostrovsky/orgs', 'repos_url': 'https://api.github.com/users/andreostrovsky/repos', 'events_url': 'https://api.github.com/users/andreostrovsky/events{/privacy}', 'received_events_url': 'https://api.github.com/users/andreostrovsky/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-19T05:05:03Z,2022-02-19T05:05:03Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([range(5), range(5), range(5)])
print(pd.style.set_properties(subset=pd.IndexSlice[1,:], **{'background-color':'#F5E3E8'}).to_latex(convert_css=True))

produces:

\begin{tabular}{lrrrrr}
 & 0 & 1 & 2 & 3 & 4 \\
0 & 0 & 1 & 2 & 3 & 4 \\
1 & {\cellcolor[HTML]{F5E3E8}} 0 & {\cellcolor[HTML]{F5E3E8}} 1 & {\cellcolor[HTML]{F5E3E8}} 2 & {\cellcolor[HTML]{F5E3E8}} 3 & {\cellcolor[HTML]{F5E3E8}} 4 \\
2 & 0 & 1 & 2 & 3 & 4 \\
\end{tabular}
```


### Issue Description

As can be seen here: [https://tex.stackexchange.com/questions/205223/cellcolor-affects-horizontal-alignment-in-table](https://tex.stackexchange.com/questions/205223/cellcolor-affects-horizontal-alignment-in-table),
the latex command `\cellcolor` must not have a space between it and the cell contents.
When using `Styler.to_latex(convert_css=True)` to convert the CSS attribute `backgound-color` to `\cellcolor`, a space is inserted between the latex command and the cell contents causing horizontal misalignment.

### Expected Behavior

The expected behavior of the above example should produce:

\begin{tabular}{lrrrrr}
 & 0 & 1 & 2 & 3 & 4 \\
0 & 0 & 1 & 2 & 3 & 4 \\
1 & {\cellcolor[HTML]{F5E3E8}}0 & {\cellcolor[HTML]{F5E3E8}}1 & {\cellcolor[HTML]{F5E3E8}}2 & {\cellcolor[HTML]{F5E3E8}}3 & {\cellcolor[HTML]{F5E3E8}}4 \\
2 & 0 & 1 & 2 & 3 & 4 \\
\end{tabular}

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.0
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.5.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46067/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46067/timeline,,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/46066,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46066/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46066/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46066/events,https://github.com/pandas-dev/pandas/issues/46066,1144196191,I_kwDOAA0YD85EMwxf,46066,PERF: dataframe.resample is very slowly in ver 1.4 and 1.4.1,"{'login': 'dovsay', 'id': 36002974, 'node_id': 'MDQ6VXNlcjM2MDAyOTc0', 'avatar_url': 'https://avatars.githubusercontent.com/u/36002974?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dovsay', 'html_url': 'https://github.com/dovsay', 'followers_url': 'https://api.github.com/users/dovsay/followers', 'following_url': 'https://api.github.com/users/dovsay/following{/other_user}', 'gists_url': 'https://api.github.com/users/dovsay/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dovsay/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dovsay/subscriptions', 'organizations_url': 'https://api.github.com/users/dovsay/orgs', 'repos_url': 'https://api.github.com/users/dovsay/repos', 'events_url': 'https://api.github.com/users/dovsay/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dovsay/received_events', 'type': 'User', 'site_admin': False}","[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-19T02:38:00Z,2022-02-19T02:38:00Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.


### Reproducible Example

    df_con = df_con.reindex(columns = ['datetime','open','high','low','close','volume','amount'])
    ##    重新采样——5 to 15
    
    df_con.drop(columns=['amount'],inplace=True)
    df_con.set_index('datetime',inplace=True)
    ohlc_dict = {                                                                                                             
            'open':'first',                                                                                                    
            'high':'max',                                                                                                       
            'low':'min',                                                                                                        
            'close': 'last',                                                                                                    
            'volume': 'sum'
            }
    o =time.time()
    df_con = df_con.resample('15min',closed='right', label='right').apply(ohlc_dict)
    print(time.time() - o)

#----------------------
# df_con  the dataframe read from the csv file includes 14690 rows
# codes print 8.608731031417847 （about 9 seconds on average）


### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : zh_CN
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.9.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
None
</details>


### Prior Performance

same code as above
It prints 0.015625476837158203（about 0.015 seconds on average）,when i change the version to 1.3.5
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46066/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46066/timeline,,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/46065,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46065/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46065/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46065/events,https://github.com/pandas-dev/pandas/pull/46065,1143972260,PR_kwDOAA0YD84zIi2p,46065,BUG: groupby().rolling(freq) with monotonic dates within groups,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/94', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94/labels', 'id': 7667127, 'node_id': 'MI_kwDOAA0YD84AdP23', 'number': 94, 'title': '1.4.2', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 15, 'state': 'open', 'created_at': '2022-02-11T09:43:27Z', 'updated_at': '2022-02-19T04:28:18Z', 'due_on': '2022-03-05T08:00:00Z', 'closed_at': None}",0,2022-02-18T23:56:21Z,2022-02-19T03:04:41Z,,MEMBER,,"- [x] closes #46061
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.4.2.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46065/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46065/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46065', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46065', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46065.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46065.patch', 'merged_at': None}"
3,https://api.github.com/repos/pandas-dev/pandas/issues/46064,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46064/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46064/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46064/events,https://github.com/pandas-dev/pandas/pull/46064,1143883713,PR_kwDOAA0YD84zIOav,46064,DOC: added examples for index assignment using Series,"{'login': 'marco-georgaklis', 'id': 51515552, 'node_id': 'MDQ6VXNlcjUxNTE1NTUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/51515552?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/marco-georgaklis', 'html_url': 'https://github.com/marco-georgaklis', 'followers_url': 'https://api.github.com/users/marco-georgaklis/followers', 'following_url': 'https://api.github.com/users/marco-georgaklis/following{/other_user}', 'gists_url': 'https://api.github.com/users/marco-georgaklis/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/marco-georgaklis/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/marco-georgaklis/subscriptions', 'organizations_url': 'https://api.github.com/users/marco-georgaklis/orgs', 'repos_url': 'https://api.github.com/users/marco-georgaklis/repos', 'events_url': 'https://api.github.com/users/marco-georgaklis/events{/privacy}', 'received_events_url': 'https://api.github.com/users/marco-georgaklis/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T22:44:22Z,2022-02-18T22:44:22Z,,NONE,,"- [x] closes #39845
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46064/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46064/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46064', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46064', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46064.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46064.patch', 'merged_at': None}"
4,https://api.github.com/repos/pandas-dev/pandas/issues/46063,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46063/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46063/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46063/events,https://github.com/pandas-dev/pandas/pull/46063,1143797205,PR_kwDOAA0YD84zH6xA,46063,BUG: BooleanArray match non-masked behavior div/pow/mod,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T21:28:21Z,2022-02-19T02:58:16Z,,MEMBER,,"- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46063/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46063/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46063', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46063', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46063.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46063.patch', 'merged_at': None}"
5,https://api.github.com/repos/pandas-dev/pandas/issues/46061,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46061/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46061/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46061/events,https://github.com/pandas-dev/pandas/issues/46061,1143734355,I_kwDOAA0YD85ELABT,46061,"BUG: groupby().rolling(""freq"") validation raises even if dates are sorted within each group","{'login': 'JILPulvino', 'id': 73976324, 'node_id': 'MDQ6VXNlcjczOTc2MzI0', 'avatar_url': 'https://avatars.githubusercontent.com/u/73976324?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JILPulvino', 'html_url': 'https://github.com/JILPulvino', 'followers_url': 'https://api.github.com/users/JILPulvino/followers', 'following_url': 'https://api.github.com/users/JILPulvino/following{/other_user}', 'gists_url': 'https://api.github.com/users/JILPulvino/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JILPulvino/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JILPulvino/subscriptions', 'organizations_url': 'https://api.github.com/users/JILPulvino/orgs', 'repos_url': 'https://api.github.com/users/JILPulvino/repos', 'events_url': 'https://api.github.com/users/JILPulvino/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JILPulvino/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],,2,2022-02-18T20:39:05Z,2022-02-18T23:12:03Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
print(pd.__version__)
test_df = pd.DataFrame({
    'Name':['L', 'L', 'L',
                    'M', 'M', 'M', 'M', 'M', 'M'],
    'ID': ['L1', 'L2', 'L3',
              'M1', 'M2', 'M3', 'M4', 'M5', 'M6'],
    'Date': [
        '2005-01-01', '2006-01-01', '2013-01-01', 
        '2005-01-01', '2006-01-01', '2006-01-01', '2017-01-01', '2006-02-01', '2006-03-01'],
    'indicator': [0, 1, 0,
                          0, 1, 0, 0, 1, 0],
    'rolling_sum':[0, 0, 1,
                              0, 0, 0, 0, 1, 2]})
test_df['Date'] = pd.to_datetime(test_df['Date'], errors='coerce')
test_df.groupby('Name').rolling('731D', on='Date')['indicator'].sum().reset_index()
```


### Issue Description

Grouping by a column and then rolling over the grouped dataframe results in `[ValueError: Date must be monotonic]()`. Ultimately, the operation should be able to produce the `rolling_sum` column in the example.

### Expected Behavior

This is not an issue in pandas `1.3.5` but is an issue in `1.4` and higher. I expect this function to create a grouped dataframe and to then perform the rolling summation on the provided column using the date window provided. 

### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46061/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46061/timeline,,,
6,https://api.github.com/repos/pandas-dev/pandas/issues/46060,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46060/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46060/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46060/events,https://github.com/pandas-dev/pandas/pull/46060,1143640899,PR_kwDOAA0YD84zHXZ6,46060,DOC: Add details to DataFrame.combine_first docstring,"{'login': 'Moisan', 'id': 31669, 'node_id': 'MDQ6VXNlcjMxNjY5', 'avatar_url': 'https://avatars.githubusercontent.com/u/31669?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Moisan', 'html_url': 'https://github.com/Moisan', 'followers_url': 'https://api.github.com/users/Moisan/followers', 'following_url': 'https://api.github.com/users/Moisan/following{/other_user}', 'gists_url': 'https://api.github.com/users/Moisan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Moisan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Moisan/subscriptions', 'organizations_url': 'https://api.github.com/users/Moisan/orgs', 'repos_url': 'https://api.github.com/users/Moisan/repos', 'events_url': 'https://api.github.com/users/Moisan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Moisan/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T19:29:12Z,2022-02-18T21:24:29Z,,CONTRIBUTOR,,"- [x] closes #41704
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46060/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46060/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46060', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46060', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46060.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46060.patch', 'merged_at': None}"
7,https://api.github.com/repos/pandas-dev/pandas/issues/46059,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46059/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46059/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46059/events,https://github.com/pandas-dev/pandas/pull/46059,1143613367,PR_kwDOAA0YD84zHRI3,46059,CI: Test various Pyarrow version on Linux,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/94', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94/labels', 'id': 7667127, 'node_id': 'MI_kwDOAA0YD84AdP23', 'number': 94, 'title': '1.4.2', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 15, 'state': 'open', 'created_at': '2022-02-11T09:43:27Z', 'updated_at': '2022-02-19T04:28:18Z', 'due_on': '2022-03-05T08:00:00Z', 'closed_at': None}",1,2022-02-18T19:09:47Z,2022-02-19T04:34:44Z,,MEMBER,,"- [x] closes #45705 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature

As discovered in https://github.com/pandas-dev/pandas/pull/46014, pyarrow v2 seems to cause timeouts in read_csv (mamba resolves to v2 but conda resolves to v6 when pyarrow is unpinned, interestingly) so skipping that version.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46059/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46059/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46059', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46059', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46059.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46059.patch', 'merged_at': None}"
8,https://api.github.com/repos/pandas-dev/pandas/issues/46058,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46058/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46058/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46058/events,https://github.com/pandas-dev/pandas/pull/46058,1143499873,PR_kwDOAA0YD84zG3b6,46058,BUG: Fix aligning a DataFrame with a Series with MultiIndex #46001,"{'login': 'johannes-mueller', 'id': 5902745, 'node_id': 'MDQ6VXNlcjU5MDI3NDU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5902745?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johannes-mueller', 'html_url': 'https://github.com/johannes-mueller', 'followers_url': 'https://api.github.com/users/johannes-mueller/followers', 'following_url': 'https://api.github.com/users/johannes-mueller/following{/other_user}', 'gists_url': 'https://api.github.com/users/johannes-mueller/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johannes-mueller/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johannes-mueller/subscriptions', 'organizations_url': 'https://api.github.com/users/johannes-mueller/orgs', 'repos_url': 'https://api.github.com/users/johannes-mueller/repos', 'events_url': 'https://api.github.com/users/johannes-mueller/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johannes-mueller/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T17:56:51Z,2022-02-18T19:40:12Z,,CONTRIBUTOR,,"When aligning a DataFrame to a Series we are using Series.reindex() to
broadcast the Series data to the new index.  That introduces NaNs when the new
index rows are not identical to the existing ones, which is not the case when
we introduce a new MultiIndex level.

In this patch we use the same approach as for aligning a Series to another
Series. That means that we have to replicate a part of Series._reindex_indexer
as DataFrame does not have it.

- [x] closes #46001 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46058/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46058/timeline,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46058', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46058', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46058.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46058.patch', 'merged_at': None}"
9,https://api.github.com/repos/pandas-dev/pandas/issues/46057,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46057/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46057/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46057/events,https://github.com/pandas-dev/pandas/pull/46057,1143476720,PR_kwDOAA0YD84zGyJw,46057,bug: styler latex longtable column count,"{'login': 'attack68', 'id': 24256554, 'node_id': 'MDQ6VXNlcjI0MjU2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/attack68', 'html_url': 'https://github.com/attack68', 'followers_url': 'https://api.github.com/users/attack68/followers', 'following_url': 'https://api.github.com/users/attack68/following{/other_user}', 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions', 'organizations_url': 'https://api.github.com/users/attack68/orgs', 'repos_url': 'https://api.github.com/users/attack68/repos', 'events_url': 'https://api.github.com/users/attack68/events{/privacy}', 'received_events_url': 'https://api.github.com/users/attack68/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T17:43:23Z,2022-02-18T17:48:37Z,,CONTRIBUTOR,,"- [x] closes #46037 
- [x] tests
- [x] whats new
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46057/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46057/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46057', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46057', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46057.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46057.patch', 'merged_at': None}"
10,https://api.github.com/repos/pandas-dev/pandas/issues/46056,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46056/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46056/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46056/events,https://github.com/pandas-dev/pandas/issues/46056,1143451823,I_kwDOAA0YD85EJ7Cv,46056,BUG: pandas.DataFrame.boxplot layout parameter creates unexpected results,"{'login': 'ryancasburn-KAI', 'id': 63560854, 'node_id': 'MDQ6VXNlcjYzNTYwODU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/63560854?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ryancasburn-KAI', 'html_url': 'https://github.com/ryancasburn-KAI', 'followers_url': 'https://api.github.com/users/ryancasburn-KAI/followers', 'following_url': 'https://api.github.com/users/ryancasburn-KAI/following{/other_user}', 'gists_url': 'https://api.github.com/users/ryancasburn-KAI/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ryancasburn-KAI/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ryancasburn-KAI/subscriptions', 'organizations_url': 'https://api.github.com/users/ryancasburn-KAI/orgs', 'repos_url': 'https://api.github.com/users/ryancasburn-KAI/repos', 'events_url': 'https://api.github.com/users/ryancasburn-KAI/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ryancasburn-KAI/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-18T17:26:40Z,2022-02-18T17:28:27Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# setup df
df1 = pd.DataFrame(np.random.randint(0,100,size=100))
df1[""Name""] = ""df1""

df2 = pd.DataFrame(np.random.randint(0,100,size=100))
df2[""Name""] = ""df2""

df3 = pd.DataFrame(np.random.randint(0,100,size=100))
df3[""Name""] = ""df3""

df4 = pd.DataFrame(np.random.randint(0,100,size=100))
df4[""Name""] = ""df4""

df = pd.concat([df1,df2,df3,df4])

# create boxplot
df.boxplot(0, by=""Name"", layout=(2,2))

plt.show()
```


### Issue Description

The all four boxplots are plotted together in the upper left corner. 
![image](https://user-images.githubusercontent.com/63560854/154732572-09cf5a65-b0a7-4fd8-a3b6-20bb797cadb6.png)


### Expected Behavior

The boxplot documentation describes the layout parameter as ""For example, (3, 5) will display the subplots using 3 columns and 5 rows, starting from the top-left."" 

To me, this indicates that the code above should create four box plots one in each corner. It is unclear what the purpose of this parameter is if all it does is put all the plots in one axes and creates empty axes.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.7.7.final.0
python-bits      : 32
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.5
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46056/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46056/timeline,,,
11,https://api.github.com/repos/pandas-dev/pandas/issues/46055,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46055/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46055/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46055/events,https://github.com/pandas-dev/pandas/pull/46055,1143435880,PR_kwDOAA0YD84zGpJX,46055,"DOC: Add ""build C extensions"" note","{'login': 'rendner', 'id': 414652, 'node_id': 'MDQ6VXNlcjQxNDY1Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/414652?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rendner', 'html_url': 'https://github.com/rendner', 'followers_url': 'https://api.github.com/users/rendner/followers', 'following_url': 'https://api.github.com/users/rendner/following{/other_user}', 'gists_url': 'https://api.github.com/users/rendner/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rendner/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rendner/subscriptions', 'organizations_url': 'https://api.github.com/users/rendner/orgs', 'repos_url': 'https://api.github.com/users/rendner/repos', 'events_url': 'https://api.github.com/users/rendner/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rendner/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T17:14:16Z,2022-02-18T18:12:34Z,,CONTRIBUTOR,,"- [x] closes #45914

This PR adds the missing information that the C extensions must be built when a local pandas repo was bind for the first time.

I also adjusted the docker commands to:
- show how you can use your forked repo (`--build-arg gh_username=yourname` was missing)
- specify the workdir `-w /home/pandas`, to directly start in the right directory","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46055/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46055/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46055', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46055', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46055.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46055.patch', 'merged_at': None}"
12,https://api.github.com/repos/pandas-dev/pandas/issues/46053,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46053/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46053/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46053/events,https://github.com/pandas-dev/pandas/pull/46053,1143397887,PR_kwDOAA0YD84zGgmw,46053,BUG: read_csv not respecting converter in all cases for index col,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}]",open,False,,[],,0,2022-02-18T16:52:15Z,2022-02-18T16:52:23Z,,MEMBER,,"- [x] closes #40589 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46053/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46053/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46053', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46053', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46053.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46053.patch', 'merged_at': None}"
13,https://api.github.com/repos/pandas-dev/pandas/issues/46052,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46052/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46052/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46052/events,https://github.com/pandas-dev/pandas/issues/46052,1143385036,I_kwDOAA0YD85EJqvM,46052,BUG: DataFrame.to_json does not take into account of time zone naive Timestamps,"{'login': 'alanhowells', 'id': 93594841, 'node_id': 'U_kgDOBZQk2Q', 'avatar_url': 'https://avatars.githubusercontent.com/u/93594841?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alanhowells', 'html_url': 'https://github.com/alanhowells', 'followers_url': 'https://api.github.com/users/alanhowells/followers', 'following_url': 'https://api.github.com/users/alanhowells/following{/other_user}', 'gists_url': 'https://api.github.com/users/alanhowells/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alanhowells/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alanhowells/subscriptions', 'organizations_url': 'https://api.github.com/users/alanhowells/orgs', 'repos_url': 'https://api.github.com/users/alanhowells/repos', 'events_url': 'https://api.github.com/users/alanhowells/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alanhowells/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T16:44:44Z,2022-02-18T16:58:49Z,,NONE,,"### Pandas Version Checks
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [ ]  I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example
```python
>>> import pandas as pd
>>> d = {'date': [pd.to_datetime('2021-02-18')], 'instant': [pd.to_datetime('2021-02-18T11:12:13')]}
>>> df = pd.DataFrame(data=d)
>>> df.to_csv()
',date,instant\r\n0,2021-02-18,2021-02-18 11:12:13\r\n'
>>> df.to_json(orient='table',index=False)
'{""schema"":{""fields"":[{""name"":""date"",""type"":""datetime""},{""name"":""instant"",""type"":""datetime""}],""pandas_version"":""1.4.0""},""data"":[{""date"":""2021-02-18T00:00:00.000Z"",""instant"":""2021-02-18T11:12:13.000Z""}]}'
```
### Issue Description
When I give a date without a time or an datetime that is time zone naïve into a dataframe, the to_json result gives UTC time zone aware instants instead of time zone naïve instants.
`to_csv` does the right thing by only giving the date, and a time zone naïve instant.
```
2021-02-18,2021-02-18 11:12:13
```
`to_json` returns a UTC time zone aware instants for both the date and the instant.
```
{""date"":""2021-02-18T00:00:00.000Z"",""instant"":""2021-02-18T11:12:13.000Z""}
```
### Expected Behaviour
I would expect the to_json to return the following
```python
>>> df.to_json(orient='table',index=False)
'{""schema"":{""fields"":[{""name"":""date"",""type"":""datetime""},{""name"":""instant"",""type"":""datetime""}],""pandas_version"":""1.4.0""},""data"":[{""date"":""2021-02-18"",""instant"":""2021-02-18T11:12:13.000""}]}'
```
Note the lack of time for the date and the lack of time zone designator for the instant.
```
{""date"":""2021-02-18"",""instant"":""2021-02-18T11:12:13.000""}
```
### Installed Versions
```python
>>> import pandas as pd
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.0.3
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46052/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46052/timeline,,,
14,https://api.github.com/repos/pandas-dev/pandas/issues/46051,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46051/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46051/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46051/events,https://github.com/pandas-dev/pandas/pull/46051,1143284661,PR_kwDOAA0YD84zGHTT,46051,ENH: Add defaultdict support for dtype in read_csv,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T15:42:49Z,2022-02-18T15:43:55Z,,MEMBER,,"- [x] closes #41574 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46051/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46051/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46051', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46051', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46051.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46051.patch', 'merged_at': None}"
15,https://api.github.com/repos/pandas-dev/pandas/issues/46050,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46050/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46050/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46050/events,https://github.com/pandas-dev/pandas/pull/46050,1143063028,PR_kwDOAA0YD84zFVmJ,46050,BUG: error in read_excel with some ods files #45598,"{'login': 'dimitra-karadima', 'id': 44123133, 'node_id': 'MDQ6VXNlcjQ0MTIzMTMz', 'avatar_url': 'https://avatars.githubusercontent.com/u/44123133?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dimitra-karadima', 'html_url': 'https://github.com/dimitra-karadima', 'followers_url': 'https://api.github.com/users/dimitra-karadima/followers', 'following_url': 'https://api.github.com/users/dimitra-karadima/following{/other_user}', 'gists_url': 'https://api.github.com/users/dimitra-karadima/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dimitra-karadima/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dimitra-karadima/subscriptions', 'organizations_url': 'https://api.github.com/users/dimitra-karadima/orgs', 'repos_url': 'https://api.github.com/users/dimitra-karadima/repos', 'events_url': 'https://api.github.com/users/dimitra-karadima/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dimitra-karadima/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T13:27:02Z,2022-02-18T15:48:30Z,,NONE,,"- [x] closes #45598 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46050/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46050/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46050', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46050', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46050.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46050.patch', 'merged_at': None}"
16,https://api.github.com/repos/pandas-dev/pandas/issues/46047,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46047/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46047/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46047/events,https://github.com/pandas-dev/pandas/pull/46047,1142725260,PR_kwDOAA0YD84zEKRw,46047,BUG: Multiindex.equals not commutative for ea dtype,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}]",open,False,,[],,3,2022-02-18T09:36:03Z,2022-02-18T12:19:33Z,,MEMBER,,"- [x] closes #46026 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46047/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46047/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46047', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46047', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46047.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46047.patch', 'merged_at': None}"
17,https://api.github.com/repos/pandas-dev/pandas/issues/46046,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46046/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46046/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46046/events,https://github.com/pandas-dev/pandas/issues/46046,1142543880,I_kwDOAA0YD85EGdYI,46046,ENH: Add `lsuffix=`/`rsuffix=` kwargs to `pd.merge()` and `df.merge()`,"{'login': 'wany-oh', 'id': 98004396, 'node_id': 'U_kgDOBddtrA', 'avatar_url': 'https://avatars.githubusercontent.com/u/98004396?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/wany-oh', 'html_url': 'https://github.com/wany-oh', 'followers_url': 'https://api.github.com/users/wany-oh/followers', 'following_url': 'https://api.github.com/users/wany-oh/following{/other_user}', 'gists_url': 'https://api.github.com/users/wany-oh/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/wany-oh/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/wany-oh/subscriptions', 'organizations_url': 'https://api.github.com/users/wany-oh/orgs', 'repos_url': 'https://api.github.com/users/wany-oh/repos', 'events_url': 'https://api.github.com/users/wany-oh/events{/privacy}', 'received_events_url': 'https://api.github.com/users/wany-oh/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-18T07:33:44Z,2022-02-18T07:33:44Z,,NONE,,"It's weird that it's in `join()` but not in `merge()`, and the current behavior (passing the length-2 list-like) of `suffixes=` kwarg is somewhat confusing syntactically.

expected:

```python
>>> df1 = pd.DataFrame({""lkey"": [""foo"", ""bar"", ""baz"", ""foo""], ""value"": [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({""rkey"": [""foo"", ""bar"", ""baz"", ""foo""], ""value"": [5, 6, 7, 8]})

>>> df1.merge(df2, left_on=""lkey"", right_on=""rkey"", lsuffix=""_left"", rsuffix=""_right"")
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46046/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46046/timeline,,,
18,https://api.github.com/repos/pandas-dev/pandas/issues/46045,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46045/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46045/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46045/events,https://github.com/pandas-dev/pandas/pull/46045,1142321035,PR_kwDOAA0YD84zCvy8,46045,FIX: clarify warning in read_sql_query(),"{'login': 'jameslamb', 'id': 7608904, 'node_id': 'MDQ6VXNlcjc2MDg5MDQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7608904?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jameslamb', 'html_url': 'https://github.com/jameslamb', 'followers_url': 'https://api.github.com/users/jameslamb/followers', 'following_url': 'https://api.github.com/users/jameslamb/following{/other_user}', 'gists_url': 'https://api.github.com/users/jameslamb/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jameslamb/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jameslamb/subscriptions', 'organizations_url': 'https://api.github.com/users/jameslamb/orgs', 'repos_url': 'https://api.github.com/users/jameslamb/repos', 'events_url': 'https://api.github.com/users/jameslamb/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jameslamb/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T04:12:48Z,2022-02-18T09:38:33Z,,CONTRIBUTOR,,"- [x] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

When using `pandas.read_sql_query()` with a non-sqlalchemy connection, the following warning is raised.

> UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy

For example, I noticed this warning today using `psycopg2` to connect to Amazon Redshift, like this:

```python
import os
import pandas
import psycopg2

query = ""SELECT * from some_table LIMIT 10""

with psycopg2.connect(...) as conn:
    df = pd.read_sql_query(sql=query, con=conn)
```

This PR proposes small grammatical changes to the warning:

* adds space to prevent unintended concatenation (e.g. `""or database""` instead of `""ordatabase""`)
* adds `.` to separate individual statements

Thanks very much for your time and consideration!","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46045/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46045/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46045', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46045', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46045.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46045.patch', 'merged_at': None}"
19,https://api.github.com/repos/pandas-dev/pandas/issues/46044,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46044/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46044/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46044/events,https://github.com/pandas-dev/pandas/issues/46044,1142141630,I_kwDOAA0YD85EE7K-,46044,BUG: wide_to_long fails/works depending on whether id variable is string/object,"{'login': 'MichaelTiemannOSC', 'id': 72577720, 'node_id': 'MDQ6VXNlcjcyNTc3NzIw', 'avatar_url': 'https://avatars.githubusercontent.com/u/72577720?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MichaelTiemannOSC', 'html_url': 'https://github.com/MichaelTiemannOSC', 'followers_url': 'https://api.github.com/users/MichaelTiemannOSC/followers', 'following_url': 'https://api.github.com/users/MichaelTiemannOSC/following{/other_user}', 'gists_url': 'https://api.github.com/users/MichaelTiemannOSC/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MichaelTiemannOSC/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MichaelTiemannOSC/subscriptions', 'organizations_url': 'https://api.github.com/users/MichaelTiemannOSC/orgs', 'repos_url': 'https://api.github.com/users/MichaelTiemannOSC/repos', 'events_url': 'https://api.github.com/users/MichaelTiemannOSC/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MichaelTiemannOSC/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-18T01:09:47Z,2022-02-18T01:09:47Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'id':['id1', 'id2'], 'nullcol':[pd.NA, 777], 'a-1':[1, 11], 'a-2':[2, 22], 'a-3':[3, 33]})

# This works when ID is an object                                                                                                                                        
print(df.dtypes)
print(pd.wide_to_long(df, ['a', 'b'], i='id', j='num', sep='-', suffix='\d'))

df.id= df.id.astype('string')

# This fails when ID is an object                                                                                                                                        
print(df.dtypes)
print(pd.wide_to_long(df, ['a', 'b'], i='id', j='num', sep='-', suffix='\d'))
```


### Issue Description

The wide_to_long function fails to transform a dataframe that has an id variable of type string, failing with this error message:

`ValueError: No objects to concatenate`

### Expected Behavior

I would expect wide_to_long to behave identically, whether the id variable is of type `string` or type `object`.  Unless the documentation specifically stated that only type `object` is supported.

### Installed Versions

I am running Pandas 1.4.1, but because once upon a time I tried to install a development environment to create a pull request, I'm being forever punished by my unforgiving OSX environment:

<details>

>>> import pandas as pd
>>> pd.show_versions()
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/pandas/util/_print_versions.py"", line 109, in show_versions
    deps = _get_dependency_info()
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/pandas/util/_print_versions.py"", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors=""ignore"")
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/pandas/compat/_optional.py"", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/importlib/__init__.py"", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ""<frozen importlib._bootstrap>"", line 1050, in _gcd_import
  File ""<frozen importlib._bootstrap>"", line 1027, in _find_and_load
  File ""<frozen importlib._bootstrap>"", line 1006, in _find_and_load_unlocked
  File ""<frozen importlib._bootstrap>"", line 688, in _load_unlocked
  File ""<frozen importlib._bootstrap_external>"", line 883, in exec_module
  File ""<frozen importlib._bootstrap>"", line 241, in _call_with_frames_removed
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/setuptools/__init__.py"", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/_distutils_hack/override.py"", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/_distutils_hack/__init__.py"", line 71, in do_override
    ensure_local_distutils()
  File ""/Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/site-packages/_distutils_hack/__init__.py"", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /Users/michael/opt/miniconda3/envs/jupyter/lib/python3.10/distutils/core.py
</details>

```
(jupyter) iMac-Pro:Downloads michael$ conda list | grep pandas
pandas                    1.4.0           py310hdd25497_0    conda-forge
pint-pandas               0.2                pyhd8ed1ab_0    conda-forge
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46044/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46044/timeline,,,
20,https://api.github.com/repos/pandas-dev/pandas/issues/46043,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46043/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46043/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46043/events,https://github.com/pandas-dev/pandas/issues/46043,1142134783,I_kwDOAA0YD85EE5f_,46043,BUG/API: Series[bool] floordiv raises but divmod does not,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 47223669, 'node_id': 'MDU6TGFiZWw0NzIyMzY2OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Numeric%20Operations', 'name': 'Numeric Operations', 'color': '006b75', 'default': False, 'description': 'Arithmetic, Comparison, and Logical operations'}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}]",open,False,,[],,0,2022-02-18T00:58:03Z,2022-02-18T21:26:07Z,,MEMBER,,"```
ser = pd.Series([True, False])

ser // ser  # <- raises

divmod(ser, ser)  # <- does not raise
```

In a number of places, specifically the extension tests TestArithmeticOps._check_divmod_op, we check for internal consistency with something like

```
res = divmod(obj, other)[0]
expected = obj // other
tm.assert_equal(res, expected)
```

In trying to adapt BooleanArray behavior to match non-masked bool dtype Series behavior (xref #41165) I found that `Series[bool]` raises on floordiv but allows divmod. 

Either both should raise or neither.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46043/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46043/timeline,,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/46041,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46041/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46041/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46041/events,https://github.com/pandas-dev/pandas/issues/46041,1141882741,I_kwDOAA0YD85ED791,46041,BUG: dataframe returned by groupby.apply() is missing outer group indices if row indices of returned dataframe are identical to those of the input dataframe,"{'login': 'julianhess', 'id': 328077, 'node_id': 'MDQ6VXNlcjMyODA3Nw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/328077?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/julianhess', 'html_url': 'https://github.com/julianhess', 'followers_url': 'https://api.github.com/users/julianhess/followers', 'following_url': 'https://api.github.com/users/julianhess/following{/other_user}', 'gists_url': 'https://api.github.com/users/julianhess/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/julianhess/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/julianhess/subscriptions', 'organizations_url': 'https://api.github.com/users/julianhess/orgs', 'repos_url': 'https://api.github.com/users/julianhess/repos', 'events_url': 'https://api.github.com/users/julianhess/events{/privacy}', 'received_events_url': 'https://api.github.com/users/julianhess/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-17T21:05:28Z,2022-02-17T21:05:28Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import numpy as np

F = pd.DataFrame({ ""a"" : np.r_[0:10], ""b"" : np.r_[0:10]//5 })

# this works as expected: the outer group indices are present
F.groupby(""b"").apply(lambda x : x.iloc[:2])

# this does not work as expected: the outer group indices are gone
F.groupby(""b"").apply(lambda x : x.iloc[:])
```


### Issue Description

`groupby.apply()` omits the outer group index in the dataframe it returns if the row indices of the returned dataframe are identical to the indices of the input dataframe. For example, given the following dataframe:

```
 F = pd.DataFrame({ ""a"" : np.r_[0:10], ""b"" : np.r_[0:10]//5 })

   a  b
0  0  0
1  1  0
2  2  0
3  3  0
4  4  0
5  5  1
6  6  1
7  7  1
8  8  1
9  9  1

```

if I group by column `b` and take only the first two rows from each group,

```
In [1]: F.groupby(""b"").apply(lambda x : x.iloc[:2])
Out[1]:
     a  b
b
0 0  0  0
  1  1  0
1 5  5  1
  6  6  1
```

the group index `b` becomes the outer index of the dataframe, as expected.  However, if I instead take all the rows from each group

```
In [2]: F.groupby(""b"").apply(lambda x : x.iloc[:])
Out[2]:
   a  b
0  0  0
1  1  0
2  2  0
3  3  0
4  4  0
5  5  1
6  6  1
7  7  1
8  8  1
9  9  1
```

the outer group index disappears. It seems that any time the row indices of the dataframe returned by `groupby.apply()` are identical to those of the input dataframe, the outer group index disappears:

```
In [3]: F.groupby(""b"").apply(lambda x : x)
Out[3]:
   a  b
0  0  0
1  1  0
2  2  0
3  3  0
4  4  0
5  5  1
6  6  1
7  7  1
8  8  1
9  9  1

In [4]: F.groupby(""b"").apply(lambda x : x + 1)
Out[4]:
    a  b
0   1  1
1   2  1
2   3  1
3   4  1
4   5  1
5   6  2
6   7  2
7   8  2
8   9  2
9  10  2
```

If the row indices of the returned dataframe differ from those of the input dataframe, the outer group index is present:

```
In [5]: F.groupby(""b"").apply(lambda x : x.iloc[np.r_[0, 4, 1, 2, 3]])
Out[5]:
     a  b
b
0 0  0  0
  4  4  0
  1  1  0
  2  2  0
  3  3  0
1 5  5  1
  9  9  1
  6  6  1
  7  7  1
  8  8  1
  
In [6]: F.groupby(""b"").apply(lambda x : x.iloc[::-1])
Out[6]:
     a  b
b
0 4  4  0
  3  3  0
  2  2  0
  1  1  0
  0  0  0
1 9  9  1
  8  8  1
  7  7  1
  6  6  1
  5  5  1
```

### Expected Behavior

I expect the outer group indices to always be present:

```
In [1]: F = pd.DataFrame({ ""a"" : np.r_[0:10], ""b"" : np.r_[0:10]//5 })

In [2]: F.groupby(""b"").apply(lambda x : x.iloc[:])
Out[2]:
   a  b
b
0  0  0  0
   1  1  0
   2  2  0
   3  3  0
   4  4  0
1  5  5  1
   6  6  1
   7  7  1
   8  8  1
   9  9  1
```

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-210-generic
Version          : #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.20.3
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.0.0.post20201207
Cython           : 0.29.22
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 0.9.0
gcsfs            : 0.8.0
matplotlib       : 3.4.2
numba            : 0.53.1
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 3.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : None
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
```

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46041/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46041/timeline,,,
22,https://api.github.com/repos/pandas-dev/pandas/issues/46040,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46040/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46040/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46040/events,https://github.com/pandas-dev/pandas/pull/46040,1141600237,PR_kwDOAA0YD84zAQUl,46040,PERF: MultiIndex slicing,"{'login': 'lukemanley', 'id': 8519523, 'node_id': 'MDQ6VXNlcjg1MTk1MjM=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8519523?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lukemanley', 'html_url': 'https://github.com/lukemanley', 'followers_url': 'https://api.github.com/users/lukemanley/followers', 'following_url': 'https://api.github.com/users/lukemanley/following{/other_user}', 'gists_url': 'https://api.github.com/users/lukemanley/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lukemanley/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lukemanley/subscriptions', 'organizations_url': 'https://api.github.com/users/lukemanley/orgs', 'repos_url': 'https://api.github.com/users/lukemanley/repos', 'events_url': 'https://api.github.com/users/lukemanley/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lukemanley/received_events', 'type': 'User', 'site_admin': False}","[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}]",open,False,,[],,0,2022-02-17T16:55:30Z,2022-02-18T09:40:03Z,,CONTRIBUTOR,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Similar to #45931, but for MultiIndex slicing.


```
import numpy as np
import pandas as pd

lev0 = pd.date_range(""2000-01-01"", ""2020-12-31"", freq=""D"")
lev1 = np.arange(10000)
mi = pd.MultiIndex.from_product([lev0, lev1])

df = pd.DataFrame({""A"": 1.0}, index=mi)

%timeit df.loc[""2010-12-31"": ""2015-12-31""]

132 ms ± 3.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)     <- main
571 µs ± 4.25 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)  <- PR
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46040/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46040/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46040', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46040', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46040.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46040.patch', 'merged_at': None}"
23,https://api.github.com/repos/pandas-dev/pandas/issues/46037,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46037/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46037/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46037/events,https://github.com/pandas-dev/pandas/issues/46037,1141485017,I_kwDOAA0YD85ECa3Z,46037,BUG: to_latex compute wrong multicolumn size in longtable environment with column_format set,"{'login': 'tgrandje', 'id': 22030685, 'node_id': 'MDQ6VXNlcjIyMDMwNjg1', 'avatar_url': 'https://avatars.githubusercontent.com/u/22030685?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tgrandje', 'html_url': 'https://github.com/tgrandje', 'followers_url': 'https://api.github.com/users/tgrandje/followers', 'following_url': 'https://api.github.com/users/tgrandje/following{/other_user}', 'gists_url': 'https://api.github.com/users/tgrandje/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tgrandje/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tgrandje/subscriptions', 'organizations_url': 'https://api.github.com/users/tgrandje/orgs', 'repos_url': 'https://api.github.com/users/tgrandje/repos', 'events_url': 'https://api.github.com/users/tgrandje/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tgrandje/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler', 'name': 'Styler', 'color': '006b75', 'default': False, 'description': 'conditional formatting using DataFrame.style'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,4,2022-02-17T15:25:38Z,2022-02-18T15:50:18Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([[1, 2, 3], [4,5,6]], columns=['A', 'B', 'C'])
print(df.style.to_latex(environment=""longtable"", column_format=""r{10cm}rr""))

# Other styling possibility :
# print(df.style.to_latex(environment=""longtable"", column_format=""r >{\columncolor{Gray}}r r""))
```


### Issue Description

The multicolumn count derived from the 'column_format' argument seems to be evaluated as the length of the passed string. This has an impact used in the longtable environment only, as it displays a  `\multicolumn{X}{r}{Continued on next page} \\`.

If you pass `column_format=""r{10cm}rr""`, you will end up with  `\multicolumn{9}{r}{Continued on next page} \\` which will trigger an error in LaTeX (9 == len(r{10cm}rr"").

Just to be clear, the complete result of the first print in the example is :
```
\begin{longtable}{r{10cm}rr}
 & A & B & C \\
\endfirsthead
 & A & B & C \\
\endhead
\multicolumn{9}{r}{Continued on next page} \\  % <-- this will trigger an error in LaTeX
\endfoot
\endlastfoot
0 & 1 & 2 & 3 \\
1 & 4 & 5 & 6 \\
\end{longtable}
```

### Expected Behavior

The column count should probably be deduced from the dataframe's shape (and the index's shape if included in the to_latex), without trying to decode the column_format string (?).

### Installed Versions

<details>

NSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-87-generic
Version          : #98~18.04.1-Ubuntu SMP Wed Sep 22 10:45:04 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.4.0
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.2.0
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.7.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46037/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46037/timeline,,,
24,https://api.github.com/repos/pandas-dev/pandas/issues/46035,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46035/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46035/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46035/events,https://github.com/pandas-dev/pandas/pull/46035,1141395675,PR_kwDOAA0YD84y_k4G,46035,ENH: Added support for the pd.read_sql to return a dictionary of all tables,"{'login': 'Pydare', 'id': 42492589, 'node_id': 'MDQ6VXNlcjQyNDkyNTg5', 'avatar_url': 'https://avatars.githubusercontent.com/u/42492589?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Pydare', 'html_url': 'https://github.com/Pydare', 'followers_url': 'https://api.github.com/users/Pydare/followers', 'following_url': 'https://api.github.com/users/Pydare/following{/other_user}', 'gists_url': 'https://api.github.com/users/Pydare/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Pydare/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Pydare/subscriptions', 'organizations_url': 'https://api.github.com/users/Pydare/orgs', 'repos_url': 'https://api.github.com/users/Pydare/repos', 'events_url': 'https://api.github.com/users/Pydare/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Pydare/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-17T14:16:06Z,2022-02-17T22:42:58Z,,CONTRIBUTOR,,"- [x] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46035/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46035/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46035', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46035', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46035.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46035.patch', 'merged_at': None}"
25,https://api.github.com/repos/pandas-dev/pandas/issues/46034,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46034/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46034/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46034/events,https://github.com/pandas-dev/pandas/pull/46034,1141338745,PR_kwDOAA0YD84y_YxU,46034,BUG: fix parquet roundtrip for Interval dtype with datetime64[ns] subtype,"{'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-17T13:27:51Z,2022-02-17T13:27:51Z,,MEMBER,,Closes #45881,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46034/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46034/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46034', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46034', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46034.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46034.patch', 'merged_at': None}"
26,https://api.github.com/repos/pandas-dev/pandas/issues/46033,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46033/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46033/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46033/events,https://github.com/pandas-dev/pandas/pull/46033,1141290483,PR_kwDOAA0YD84y_OjR,46033,FIX # 45957 issue read_csv with empty list,"{'login': 'profMsaif', 'id': 19476974, 'node_id': 'MDQ6VXNlcjE5NDc2OTc0', 'avatar_url': 'https://avatars.githubusercontent.com/u/19476974?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/profMsaif', 'html_url': 'https://github.com/profMsaif', 'followers_url': 'https://api.github.com/users/profMsaif/followers', 'following_url': 'https://api.github.com/users/profMsaif/following{/other_user}', 'gists_url': 'https://api.github.com/users/profMsaif/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/profMsaif/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/profMsaif/subscriptions', 'organizations_url': 'https://api.github.com/users/profMsaif/orgs', 'repos_url': 'https://api.github.com/users/profMsaif/repos', 'events_url': 'https://api.github.com/users/profMsaif/events{/privacy}', 'received_events_url': 'https://api.github.com/users/profMsaif/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,4,2022-02-17T12:43:15Z,2022-02-18T21:54:21Z,,NONE,,"- [ ] closes #45957 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46033/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46033/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46033', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46033', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46033.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46033.patch', 'merged_at': None}"
27,https://api.github.com/repos/pandas-dev/pandas/issues/46032,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46032/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46032/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46032/events,https://github.com/pandas-dev/pandas/issues/46032,1141083869,I_kwDOAA0YD85EA47d,46032,ENH: Add mode for `to_pickle`,"{'login': 'thatlittleboy', 'id': 30731072, 'node_id': 'MDQ6VXNlcjMwNzMxMDcy', 'avatar_url': 'https://avatars.githubusercontent.com/u/30731072?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/thatlittleboy', 'html_url': 'https://github.com/thatlittleboy', 'followers_url': 'https://api.github.com/users/thatlittleboy/followers', 'following_url': 'https://api.github.com/users/thatlittleboy/following{/other_user}', 'gists_url': 'https://api.github.com/users/thatlittleboy/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/thatlittleboy/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/thatlittleboy/subscriptions', 'organizations_url': 'https://api.github.com/users/thatlittleboy/orgs', 'repos_url': 'https://api.github.com/users/thatlittleboy/repos', 'events_url': 'https://api.github.com/users/thatlittleboy/events{/privacy}', 'received_events_url': 'https://api.github.com/users/thatlittleboy/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-17T09:31:14Z,2022-02-17T09:31:14Z,,NONE,,"#### Is your feature request related to a problem?

The `df.to_csv()` function has a `mode` parameter that allows the user to specify the [file mode](https://docs.python.org/3/library/functions.html#open) when writing.
I usually use `mode='x'` to avoid writing over the existing file, as caution.

Is there any specific reason why `to_pickle` and co. doesn't have the same parameter?

#### Describe the solution you'd like

I see that `mode` for `df.to_csv` is implemented/used via the `get_handle` function: https://github.com/pandas-dev/pandas/blob/1.4.x/pandas/io/formats/csvs.py#L243

`df.to_pickle` also has the same function call but mode is fixed to `wb`: https://github.com/pandas-dev/pandas/blob/1.4.x/pandas/io/pickle.py#L99

Can `mode` be exposed as an API to the end user, with additional checks that the user specifies binary (`b`) if needed?

#### API breaking implications

Not sure, probably none?

#### Additional info

docs for to_pickle: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html
docs for to_csv: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

#### Describe alternatives you've considered

End user manually checks if file exists before running `df.to_pickle`.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46032/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46032/timeline,,,
28,https://api.github.com/repos/pandas-dev/pandas/issues/46031,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46031/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46031/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46031/events,https://github.com/pandas-dev/pandas/issues/46031,1141073824,I_kwDOAA0YD85EA2eg,46031,BUG: .astype date conversion from object to datetime switches months and days,"{'login': 'eliyahuA', 'id': 45657774, 'node_id': 'MDQ6VXNlcjQ1NjU3Nzc0', 'avatar_url': 'https://avatars.githubusercontent.com/u/45657774?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/eliyahuA', 'html_url': 'https://github.com/eliyahuA', 'followers_url': 'https://api.github.com/users/eliyahuA/followers', 'following_url': 'https://api.github.com/users/eliyahuA/following{/other_user}', 'gists_url': 'https://api.github.com/users/eliyahuA/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/eliyahuA/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/eliyahuA/subscriptions', 'organizations_url': 'https://api.github.com/users/eliyahuA/orgs', 'repos_url': 'https://api.github.com/users/eliyahuA/repos', 'events_url': 'https://api.github.com/users/eliyahuA/events{/privacy}', 'received_events_url': 'https://api.github.com/users/eliyahuA/received_events', 'type': 'User', 'site_admin': False}","[{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries', 'name': 'Timeseries', 'color': 'AFEEEE', 'default': False, 'description': None}, {'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,4,2022-02-17T09:23:29Z,2022-02-18T19:21:01Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import numpy as np

print(pd.__version__)
df = pd.DataFrame({'A': ['01/07/2021']})
print(df)
pd.set_option('display.date_dayfirst', True)
date_df = df.astype(dtype={'A': 'datetime64'})
date_df_np = df.astype(dtype={'A': np.datetime64})
print(date_df)
print(date_df_np)

Output:

            A
0  01/07/2021
           A
0 2021-01-07
           A
0 2021-01-07
```


### Issue Description

When converting a string (object) dtype to a datetime dtype with DataFrame astype method, the date format is inferred according to United States notation, despite the setting of display.date_dayfirst



### Expected Behavior

Yes, it's possible to use pd.to_datetime, but for simple cases it's cumbersome to have to break the symmetry between how you would coerce other types and how you coerce datetimes.

Expected Output:

            A
0  01/07/2021
           A
0 2021-07-01
           A
0 2021-07-01

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 63 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Hebrew_Israel.1255
pandas           : 1.4.1
numpy            : 1.22.0
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46031/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46031/timeline,,,
29,https://api.github.com/repos/pandas-dev/pandas/issues/46030,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46030/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46030/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46030/events,https://github.com/pandas-dev/pandas/issues/46030,1140981307,I_kwDOAA0YD85EAf47,46030,"BUG: lib.is_all_arraylike should not assume a _data attribute means ""array-like"".","{'login': 'zpincus', 'id': 174217, 'node_id': 'MDQ6VXNlcjE3NDIxNw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/174217?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zpincus', 'html_url': 'https://github.com/zpincus', 'followers_url': 'https://api.github.com/users/zpincus/followers', 'following_url': 'https://api.github.com/users/zpincus/following{/other_user}', 'gists_url': 'https://api.github.com/users/zpincus/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zpincus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zpincus/subscriptions', 'organizations_url': 'https://api.github.com/users/zpincus/orgs', 'repos_url': 'https://api.github.com/users/zpincus/repos', 'events_url': 'https://api.github.com/users/zpincus/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zpincus/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-17T07:44:41Z,2022-02-17T07:44:41Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

class A:
    _dat = 5

# succeeds
pd.DataFrame(data={1:range(10), 2:range(10)}, index = [A() for a in range(10)])

class B:
    _data = 5

# fails, as B instances are assumed array-like, so Pandas tries and fails to make a MultiIndex
pd.DataFrame(data={1:range(10), 2:range(10)}, index = [B() for a in range(10)])
```


### Issue Description

In `pandas.core.indexes.base`, `ensure_index()` calls `pandas.lib.is_all_arraylike` to determine whether a list of entries should be treated as a regular index or a multi-index. 

However, this function will incorrectly assume that any instance with a `_data` attribute is ""array-like"". This is highly nonstandard. It would seem better to look for something canonical such as `__array_interface__` or similar. Just looking for a `_data` attribute is both nonspecific (lots of classes have `_data` attributes) and misses any array-like instances that don't happen to have a `_data`. (Numpy arrays don't have `_data`, even: `is_all_arraylike` has to special-case for actual arrays...)

The result of this is that instances of non-array-like classes that happen to have `_data` attributes cannot be pandas indices.

Here's the source in master:
https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/lib.pyx#L762


### Expected Behavior

`pandas.lib.is_all_arraylike` should correctly report array-like things as array-like, and things like `class B` above correctly as not array-like.

### Installed Versions

My versions don't matter (they're below anyway), as the offending code is in master:
https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/lib.pyx#L762

<details>

pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-18-cloud-amd64
Version          : #1 SMP Debian 4.19.208-1 (2021-09-29)
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.15.0
pyarrow          : 4.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : 1.4.28
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.0
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46030/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46030/timeline,,,
